### ISSUE TITLE
Resize DeskPad window?

### ISSUE THREAD

**Issue by thefakeplace** [Stengo/DeskPad#11]
Would like this feature-- I need my virtual display to be at a higher resolution than my physical screen, and right now it takes up too much space on my screen.

**Comment by jakobwarnhjelm** [comment]
@thefakeplace SwitchResX might be worth a try, allows for custom resolutions for connected displays

**Comment by thefakeplace** [comment]
I can already drive the virtual display at 4k, for example-- but my actual display's resolution is 1080p, so the window gets cut off.

Custom res would help if I wanted to go lower and couldn't, but I want it at 4k. Just want it to be scaled down to fit on my laptop screen.

**Comment by EarlOrlando** [comment]
This request is addressed in https://github.com/Stengo/DeskPad/pull/16. 

While the pull request is accepted, you can test the features in https://github.com/EarlOrlando/DeskPad/tree/earl/new_features.

**Comment by Stengo** [comment]
Resolved via https://github.com/Stengo/DeskPad/pull/16 🎉
