### ISSUE TITLE
Can't use cursor inside Deskpad display

### ISSUE THREAD

**Issue by jakobwarnhjelm** [Stengo/DeskPad#12]
Symptom: when I click or type inside the deskpad window, the click is registered in the real display, not inside the app open in deskpad.

I've managed to move windows into Deskpad monitor using Rectangles features to move windows to other screen. But when the window/app is inside Deskpad I can't reach it using mouse or keyboard.

I'm not sure if this is related to MacOs or Deskpad.

**Comment by Stengo** [comment]
Make sure to check out where your DeskPad display is arranged via the systems Settings app. Moving the mouse over in that direction moved it onto the virtual DeskPad display, just like it would with a real monitor 🙂 

<img width="827" alt="Screenshot 2023-10-11 at 17 59 52" src="https://github.com/Stengo/DeskPad/assets/12018882/d39dfb23-926a-4135-90e8-13a8c4e6bb29">

**Comment by EarlOrlando** [comment]
This request is addressed in https://github.com/Stengo/DeskPad/pull/16. 

While the pull request is accepted, you can test the features in https://github.com/EarlOrlando/DeskPad/tree/earl/new_features.

**Comment by Stengo** [comment]
Resolved via https://github.com/Stengo/DeskPad/pull/16 🎉
