### ISSUE TITLE
[Feature Request] Register mouse clicks within the window

### ISSUE THREAD

**Issue by az-zendesk** [Stengo/DeskPad#13]
First of all: GREAT JOB! This app is an invaluable when I work on ultra wide monitors with ratio such as 32:9 and need to share a couple of apps along each other :) 

Now back to business ;)

**Problem Statement**
Time and time, when I use the app, I'm not sure, if my cursor is hoovering over virtual display, or over the DeskPad window on my real display.

I regularly try to click something over the DeskPad window and get frustrated that apps are unresponsive :)

**Suggested solution**
Can you translate `bounds(X,Y)` clicks on the DeskPad App Window, to the `frame(X,Y)` location on the virtual display? This would probably require accessibility permission so it could be opt-in feature in the options, to not trigger permissions alert for everybody.

Next step would be to support drag and drop, etc, but simple single clicks would be a huge improvement over nothing.

Alternative solution would be to (right after click on the window) "teleport" the cursor to the virtual display to the click location, and then do the click. This way, drag and drop, and all features would work by themselves.

Thanks in advance!

**Comment by acrylicus** [comment]
+1 on this, app would be PERFECT with this functionality added

**Comment by EarlOrlando** [comment]
I'm working on it! I'll open a pull request soon 😃

**Comment by EarlOrlando** [comment]
This request is addressed in https://github.com/Stengo/DeskPad/pull/16. 

While the pull request is accepted, you can test the features in https://github.com/EarlOrlando/DeskPad/tree/earl/new_features.

**Comment by Stengo** [comment]
Resolved via https://github.com/Stengo/DeskPad/pull/16 🎉
