### ISSUE TITLE
[Feature Request] Provide DeskPad as a Homebrew Cask for Simplified Installation/Upgrading

### ISSUE THREAD

**Issue by frederikb** [Stengo/DeskPad#15]
Hey there, I'm currently trying out your app and it looks very promising so far. Thanks!

### Problem Statement
Currently, the process of installing and upgrading DeskPad on macOS is a manual step and somewhat cumbersome. Many users, including myself, prefer utilizing package managers such as Homebrew for managing software installations and upgrades due to its simplicity and command-line interface.

### Suggested Solution
I propose that DeskPad be made available as a [Homebrew](https://brew.sh) cask, which would significantly streamline the installation and upgrading process. Users would be able to execute `brew install --cask deskpad` for initial installation and `brew upgrade --cask deskpad` for upgrading to newer versions, making the process more convenient and aligned with the preferences of many macOS users.

Furthermore, providing DeskPad as a cask on Homebrew could potentially broaden its user base, as Homebrew is a widely-adopted package manager within the macOS community. There is a fairly straightforward guide on [how to provide an app as a cask](https://docs.brew.sh/Adding-Software-to-Homebrew#casks).

Let me know, whether this is something you're interested in and I'll take a crack at it.

**Comment by frederikb** [comment]
I've prepared a basic [cask](https://github.com/frederikb/homebrew-cask/blob/add-deskpad/Casks/d/deskpad.rb). 

Curently `brew audit --cask --new deskpad` fails, because the app is not signed and notarized (see #17). I'm not sure if this would deny any PR to the Homebrew cask tap, so I'm holding off on that for now.

**Comment by frederikb** [comment]
I've checked in with the HomeBrew maintainers: unsigned/unnotarized apps cannot be included in the main casks tap.

The choices are either getting that done or creating and maintaining an custom [tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap).

**Comment by Stengo** [comment]
Thank you for looking into this! As mentioned on the other issue, the app should now be properly notarized 🙂

**Comment by Stengo** [comment]
Thank you @frederikb for submitting DeskPad to the brew repository! I'll go ahead and close this issue 🙂
