### ISSUE TITLE
[Bug] macOS Gatekeeper Rejection Due to Lack of Signature and Notarization

### ISSUE THREAD

**Issue by frederikb** [Stengo/DeskPad#17]
Upon downloading and attempting to run the DeskPad application on macOS Sonoma, I encountered a rejection by the Gatekeeper. 
![image](https://github.com/Stengo/DeskPad/assets/232148/12ebcc71-9a83-4208-bbc5-c24b437e0c06)
To proceed, you need to perform the usual steps to add an exception in order to allow the app to run. I delved deeper into the application's signature status using Apparency and here's what I found:

1. **Signed by**: The signature does not match any Gatekeeper policy.
The DeskPad.app is signed by "Apple Development: Bastian Andelefski (DQ9U5WWMJR)," a certificate issued by Apple to a third-party developer for the purposes of signing apps during development and testing phase. Unfortunately, the signature does not align with any established Gatekeeper policy which results in a default prohibition of code execution on macOS.
![image](https://github.com/Stengo/DeskPad/assets/232148/3c49856c-dcc2-416c-9bba-368cdc6224c4)

3. **Gatekeeper Status**: The app is flagged as "Rejected." 
This status is assigned because the app is signed with a certificate not recognized as trusted by Gatekeeper (or possibly even by macOS). This could arise if the component was signed with a third-party certificate, or an Apple-issued certificate but not of the Developer ID variety.
![image](https://github.com/Stengo/DeskPad/assets/232148/e7884fe1-8067-4ca1-9b95-fab39b4a0c10)

4. **Notarization Status**: No notarization was detected for DeskPad.app. 
This situation presents a hurdle as the exceptions required for allowing code execution will not be met. Specifically, even if the app was signed with an Apple-issued Developer ID certificate it would not run without being notarized. 
![image](https://github.com/Stengo/DeskPad/assets/232148/1995394a-5af0-486b-8629-40cc3e1c97ff)

This issue became apparent while I was preparing a Homebrew cask for DeskPad, where the audit step failed due to the absence of a signature and notarization for the app.

I understand that acquiring a Developer ID and notarizing the app involves costs, and might be a significant ask for a free open source application. I just wanted to open up this issue to highlight the topic, because you did make the effort to sign it with a signature for v1.1.

[Additional resourced about code signing and notarization](https://developer.apple.com/forums/thread/707080/).

**Comment by Stengo** [comment]
The issue should be resolved in release v1.2 🙂 
https://github.com/Stengo/DeskPad/releases/tag/v1.2
