### ISSUE TITLE
Apps moved to DeskPad are not shown

### ISSUE THREAD

**Issue by nift-d** [Stengo/DeskPad#19]
Hardware/OS configuration:
- MacBook Pro 2023
- MacOS 14.1.1

Version:
- deskpad: 1.3.1, installed via homebrew

Symptoms:
- keeps asking for permissions that are already granted
- apps moved to the DeskPad screen are not displayed, the DeskPad screen stays black, blue or white

Steps to reproduce:
- App asks for permission to record screen at every start, despite the fact its already granted:
<img width="451" alt="image" src="https://github.com/Stengo/DeskPad/assets/88383796/f4a3b41f-3f9d-45e9-8736-c0c04bc57527">

- I choose "open system settings" and get redirected to said settings, where the permission is already shown:
<img width="467" alt="image" src="https://github.com/Stengo/DeskPad/assets/88383796/11e8792b-c38c-4d1e-ae1d-df21a9d2fa41">

- the app is open and gets displayed in the display settings as well
<img width="427" alt="image" src="https://github.com/Stengo/DeskPad/assets/88383796/8bf2b385-313c-419d-9200-103660f091b0">

- when i move apps to DeskPad screen nothing is shown
<img width="1003" alt="image" src="https://github.com/Stengo/DeskPad/assets/88383796/32126a23-e000-437f-a742-2b2175826319">

Permissions granted:
- Screen Recording
- Accessibility

side notes:
- DeskPad I used v1.1 and it worked
- the problem started with v1.2 before switching to the brew package.

**Comment by Stengo** [comment]
Hey!
Try deleting the system setting permission, restart the new installation of DeskPad, grant the permission but deny restarting via the dialog, then restart manually 🙂 

I've had this problem a few times during development. macOS doesn't distinguish between multiple installations of the same app in the permissions screen, so it keeps the granted permission for the old version but doesn't add a new one for the new version (but also doesn't allow the new version to do the restricted things) 😅

**Comment by nift-d** [comment]
Not sure if I understand correctly:
1. deleted the permission for Accessibility and Screen Recording
2. removed deskpad `brew remove deskapp`
3. installed deskpad `brew install deskpad` again
4. started DeskPad via spotlight, clicked "Open System Settings" in the appearing popup and only allowed Screen Recording but with denying the restart by clicking "Later"
5. restarted manually
6. and I was faced with the same request again:
<img width="459" alt="image" src="https://github.com/Stengo/DeskPad/assets/88383796/048060ac-be83-4eb6-8873-e7d52210a309">

I did the same but with quitting and restarting right after allowing Screen Recording, but with no change..

**Comment by Stengo** [comment]
Hm, that's odd 🤔 I'd recommend playing around a bit more with deleting the permission.

It's really important to launch the same version of DeskPad throughout the whole process, as spotlight for example might still link to an older one that's perhaps in a download folder or something similar (at least that happened to me a few times 😄). So if you want to be extra sure perhaps find the executable and launch it directly.

Other than that I don't currently have any tips for how to proceed 😕

**Comment by nift-d** [comment]
I tried everything even rebooting and clearing the brew cache for making sure it downloads the package again. it is impossible to use now..

**Comment by nift-d** [comment]
ok, took the package from github again and it works now. maybe due to the homebrew package?
