### ISSUE TITLE
Allow resolutions larger than physical display

### ISSUE THREAD

**Issue by seanf** [Stengo/DeskPad#2]
To turn things inside out a bit: would it be possible to implement support for a virtual display which is larger or wider than my physical display, combined with the ability to pan? 

For instance, if I only have a 16:9 monitor, a virtual ultrawide monitor with easy panning could help with viewing ultrawide screenshares by others.

**Comment by EarlOrlando** [comment]
This request is addressed in https://github.com/Stengo/DeskPad/pull/16. 

While the pull request is accepted, you can test the features in https://github.com/EarlOrlando/DeskPad/tree/earl/new_features.

**Comment by Stengo** [comment]
Resolved via https://github.com/Stengo/DeskPad/pull/16 🎉

**Comment by Stengo** [comment]
Resolved via https://github.com/Stengo/DeskPad/pull/16 🎉
