### ISSUE TITLE
DeskPad Window blank or blue, no content is shown

### ISSUE THREAD

**Issue by TomTomNavigator** [Stengo/DeskPad#22]
Just documenting here: 

I had a weird issue where the DeskPad Window was just blue and it was requesting Screen Sharing permissions at every startup. 
Disabling and enabling the permission did not change anything. Also reinstalling or using the Homebrew version did not fix this. 

I had to reset the Screen Sharing permissions with 

`tccutil reset ScreenCapture com.stengo.DeskPad`

Maybe that helps someone else with the same problem! :-)

**Comment by brunovg** [comment]
I had the same problem as @TomTomNavigator, and that command line also worked for me.
Maybe it would be nice to add this kind of info on the Readme page.
By the way, congrats for the project 👍🏻
