### ISSUE TITLE
Can't see mouse cursor

### ISSUE THREAD

**Issue by citypaul** [Stengo/DeskPad#29]
Hey there!

Great app, love the concept. I think it will help me from accidentally sharing chat windows when I'm sharing my screen.

It is working for me and I can actually use the mouse inside it, but I can't see the mouse cursor itself, which makes it quite difficult to use. Is this a known issue? I'm on `15.0 Beta (24A5320a)` if that helps!

**Comment by tombenninger** [comment]
I just upgraded to the MacOS 15.0 release and I'm now seeing this issue, though I did not have it previously.

**Comment by norison** [comment]
Same for me

**Comment by guysbrown** [comment]
I also have the same issue. I upgraded to MacOS 15.0 and can no longer see the mouse cursor. I hope it's fixed soon. I love DeskPad and use it daily!

**Comment by gamezinfantes** [comment]
same, after upgrading to 15.0 mouse is not visible anymore

**Comment by kernel-sanders** [comment]
As pointed out by #24 if you download [Advanced Screen Share](https://apps.apple.com/us/app/advanced-screen-share/id1597458111?mt=12) and leave it running Deskpad will show the mouse cursor. The free version of Advanced Screen Share is fine, it just needs to be running at the same time.

Hope this gets fixed so we don't need this workaround - love Deskpad!

**Comment by kaluzapatryk** [comment]
The workaround works, thanks! :)

**Comment by men232** [comment]
I hope my pull request will be merged, this works for me :)

**Comment by citypaul** [comment]
Awesome @men232! I hope this get merged soon, thanks for the fix!

**Comment by stanleyswiss** [comment]
Thanks @men232, your fix worked for me too, just in time for several customer presentations I have to do today 👍

**Comment by Stengo** [comment]
Fixed by #32
