### ISSUE TITLE
cursor disappears in MacOS Sequoia 15.0

### ISSUE THREAD

**Issue by e60mma** [Stengo/DeskPad#33]
Summary: 
Cursor disappears when moved over virtual display with DeskPad launched. Cursor interactions are still functional as clicks and movement of cursor is observed when hovering over interactive assets on the UI.  However, cursor itself is not visible as it is moved when on the virtual display. 

Expected behavior: 
Cursor is visible during all movement on physical and virtual displays.

**Comment by mithun-daa** [comment]
I am seeing similar behaviour.

**Comment by eduardo-svg** [comment]
Same behavior on Macbook Pro M1 running Sequoia

**Comment by cirby944** [comment]
Same behavior for me as well. When I did a screen recording of the virtual display, I noticed that the recording showed the cursor, but I could not see it while creating the recording.

**Comment by meczero** [comment]
Same here! I'm on an 2019 Intel mac

**Comment by e60mma** [comment]
Just updated to Sequoia 15.0.1 today and issue persists.

**Comment by Stengo** [comment]
Fixed by #32
