### ISSUE TITLE
DeskPad display doesn't respond like physical display

### ISSUE THREAD

**Issue by KrysN007** [Stengo/DeskPad#8]
I just got an ultruwidescreen for work and was so thrilled to find this! I installed the app no problem, but when I open it, and the DeskPad display opens, I can't actually use it, i.e. I can't open my applications on it. I click on the icons in my control dock and they don't open?

**Comment by jordanrvillarreal** [comment]
First thing you need to do is position it within the OS as if it is a physical monitor. Does that mean it's to the left or right if your display? Or above or below? Set that up in your display options. 

Then you drag the applications off that side of the screen, into the virtual monitor.
